update: last

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,153 +2,149 @@
 
 set -euo pipefail
 
+if [[ $# -gt 0 ]] && [[ $1 == "--clean" ]]; then
+    rm -rf "$HOME/.cache/dotfiles/"
+    shift 1
+fi
+
 source "./header"
 
 sudo -v
 clear
 
-setup_os() {
-    case "$OS" in
-    debian)
-        if [[ ! -f /etc/apt/sources.list.d/debian.sources ]]; then
-            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list
-            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
-            echo "deb http://security.debian.org/debian-security ${VERSION_CODENAME}-security main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
+setup_debian() {
+    if ! [[ -f /etc/apt/sources.list.d/debian.sources ]]; then
+        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list
+        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
+        echo "deb http://security.debian.org/debian-security ${VERSION_CODENAME}-security main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
 
-            sudo apt modernize-sources -y
+        sudo apt modernize-sources -y
 
-            echo "# DOTFILES" | sudo tee -a /etc/apt/sources.list.d/debian.sources
-            echo "# Sources list modified $(date)" | sudo tee -a /etc/apt/sources.list.d/debian.sources
-        elif ! grep '^# DOTFILES' /etc/apt/sources.list.d/debian.sources &>/dev/null; then
-            sudo rm -rf /etc/apt/sources.list.d/debian.sources
+        echo "# DOTFILES" | sudo tee -a /etc/apt/sources.list.d/debian.sources
+        echo "# Sources list modified $(date)" | sudo tee -a /etc/apt/sources.list.d/debian.sources
+    elif ! grep '^# DOTFILES' /etc/apt/sources.list.d/debian.sources &>/dev/null; then
+        sudo rm -rf /etc/apt/sources.list.d/debian.sources
 
-            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list
-            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
-            echo "deb http://security.debian.org/debian-security ${VERSION_CODENAME}-security main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
+        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME} main contrib non-free non-free-firmware" | sudo tee /etc/apt/sources.list
+        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-updates main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
+        echo "deb http://security.debian.org/debian-security ${VERSION_CODENAME}-security main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
 
-            sudo apt modernize-sources -y
+        sudo apt modernize-sources -y
 
-            echo -e "\n# DOTFILES" | sudo tee -a /etc/apt/sources.list.d/debian.sources
-            echo -e "# Sources list modified $(date)" | sudo tee -a /etc/apt/sources.list.d/debian.sources
-        fi
+        echo -e "\n# DOTFILES" | sudo tee -a /etc/apt/sources.list.d/debian.sources
+        echo -e "# Sources list modified $(date)" | sudo tee -a /etc/apt/sources.list.d/debian.sources
+    fi
 
-        if [[ ! -f /etc/apt/sources.list.d/backports.lists ]] && [[ ! -f /etc/apt/sources.list.d/backports.sources ]]; then
-            echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list.d/backports.list
-            sudo apt modernize-sources -y
-        fi
+    if ! [[ -f /etc/apt/sources.list.d/backports.lists ]] && [[ ! -f /etc/apt/sources.list.d/backports.sources ]]; then
+        echo "deb http://deb.debian.org/debian ${VERSION_CODENAME}-backports main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list.d/backports.list
+        sudo apt modernize-sources -y
+    fi
 
-        sudo apt-get update -y
-        if apt list --upgradable; then
-            sudo apt-get upgrade -y
-        fi
-        ;;
-    arch)
-        if [[ ! -f /etc/ld.so.conf.d/local.conf ]]; then
-            echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/local.conf
-            sudo ldconfig
-        fi
+    sudo apt-get update -y
+    if apt list --upgradable; then
+        sudo apt-get upgrade -y
+    fi
 
-        if grep -E '^#Color' /etc/pacman.conf &>/dev/null; then
-            sudo sed -i '/^#Color/s/^#//' /etc/pacman.conf
-        fi
-
-        if grep -E '^#ParallelDownloads[[:space:]]*=[[:space:]]*[0-9]\+' /etc/pacman.conf &>/dev/null; then
-            sudo sed -i '/^#ParallelDownloads[[:space:]]*=[[:space:]]*[0-9]\+/s/^#//' /etc/pacman.conf
-        fi
-
-        if grep -A 1 '^#[[:space:]]*\[multilib\]' /etc/pacman.conf &>/dev/null; then
-            sudo sed -i '/^#[[:space:]]*\[multilib\]/,/^#[[:space:]]*Include = \/etc\/pacman.d\/mirrorlist/s/^#//' /etc/pacman.conf
-        fi
-
-        if [[ ! -f /usr/lib/systemd/system/pacman-update.service ]]; then
-            sudo cp ./.contents/pacman-update.service /usr/lib/systemd/system/
-        fi
-
-        if ! sudo systemctl is-active pacman-update &>/dev/null; then
-            sudo systemctl enable pacman-update
-        fi
-
-        sudo pacman -Sy
-        if sudo pacman -Qu; then
-            sudo pacman -Syu --noconfirm
-        fi
-        ;;
-    esac
-}
-
-install_git() {
-    case "$OS" in
-    arch)
-        sudo pacman -Sy
-        sudo pacman -S --noconfirm git
-        ;;
-    debian)
+    if [[ $ISGIT == "$ERROR" ]]; then
         sudo apt-get update -y
         sudo apt install -y git
-        ;;
-    esac
-}
+    fi
 
-install_python() {
-    case "$OS" in
-    arch)
-        sudo pacman -Sy
-        sudo pacman -S --noconfirm python
-        ;;
-    debian)
+    if [[ $ISPYTHON == "$ERROR" ]]; then
         sudo apt-get update -y
         sudo apt install -y python3
-        ;;
-    esac
-}
+    fi
 
-install_pipx() {
-    case "$OS" in
-    arch)
-        sudo pacman -Sy
-        sudo pacman -S --noconfirm python-pipx
-        ;;
-    debian)
+    if [[ $ISPIPX == "$ERROR" ]]; then
         sudo apt-get update -y
         sudo apt install -y pipx
-        ;;
-    esac
+    fi
+}
+
+setup_arch() {
+    if ! [[ -f /etc/ld.so.conf.d/local.conf ]]; then
+        echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/local.conf
+        sudo ldconfig
+    fi
+
+    if grep -E '^#Color' /etc/pacman.conf &>/dev/null; then
+        sudo sed -i '/^#Color/s/^#//' /etc/pacman.conf
+    fi
+
+    if grep -E '^#ParallelDownloads[[:space:]]*=[[:space:]]*[0-9]\+' /etc/pacman.conf &>/dev/null; then
+        sudo sed -i '/^#ParallelDownloads[[:space:]]*=[[:space:]]*[0-9]\+/s/^#//' /etc/pacman.conf
+    fi
+
+    if grep -A 1 '^#[[:space:]]*\[multilib\]' /etc/pacman.conf &>/dev/null; then
+        sudo sed -i '/^#[[:space:]]*\[multilib\]/,/^#[[:space:]]*Include = \/etc\/pacman.d\/mirrorlist/s/^#//' /etc/pacman.conf
+    fi
+
+    if ! [[ -f /usr/lib/systemd/system/pacman-update.service ]]; then
+        sudo cp ./.contents/pacman-update.service /usr/lib/systemd/system/
+    fi
+
+    if ! sudo systemctl is-active pacman-update &>/dev/null; then
+        sudo systemctl enable pacman-update
+    fi
+
+    sudo pacman -Sy
+    if sudo pacman -Qu; then
+        sudo pacman -Syu --noconfirm
+    fi
+
+    if [[ $ISGIT == "$ERROR" ]]; then
+        sudo pacman -Sy
+        sudo pacman -S --noconfirm git
+    fi
+
+    if [[ $ISPYTHON == "$ERROR" ]]; then
+        sudo pacman -Sy
+        sudo pacman -S --noconfirm python
+    fi
+
+    if [[ $ISPIPX == "$ERROR" ]]; then
+        sudo pacman -Sy
+        sudo pacman -S --noconfirm python-pipx
+    fi
+
+    # local AUR_DIR=$HOME/.cache/dotfiles/aur_helper
+    # if ! command -v "${AUR_HELPER}"; then
+    #     clear
+    #     echo -e "Installing ${AUR_HELPER}"
+    #     sleep 2
+    #     sudo pacman -Sy
+    #     sudo pacman -S --noconfirm base-devel git
+    #     if ! [[ -d "${AUR_DIR}" ]]; then
+    #         git clone https://aur.archlinux.org/${AUR_HELPER}-bin.git "${AUR_DIR}"
+    #     fi
+    #     makepkg --noconfirm -sri -D "${AUR_DIR}"
+    # fi
 }
 
 echo -e "* Preparing OS"
-if ! setup_os >/dev/null 2>"$LOGFILE"; then
-    echo -e "$ERROR, Failed preparing os, see log $LOGFILE"
+case "${OS}" in
+debian)
+    if ! setup_debian >/dev/null 2>$LOGFILE; then
+        clear
+        echo -e "$ERROR, Failed to prepare OS check log $LOGFILE"
+        exit 1
+    fi
+    ;;
+arch)
+    if ! setup_arch >/dev/null 2>$LOGFILE; then
+        clear
+        echo -e "$ERROR, Failed to prepare OS check log $LOGFILE"
+        exit 1
+    fi
+    ;;
+*)
+    echo -e "$ERROR, ${OS}, is not supported"
     exit 1
-fi
-
-if [[ $ISGIT == "$ERROR" ]]; then
-    echo -e "** Installing git"
-    if ! install_git >/dev/null 2>"$LOGFILE"; then
-        clear
-        echo -e "$ERROR, Failed to install git, see log $LOGFILE"
-        exit 1
-    fi
-fi
-
-if [[ $ISPYTHON == "$ERROR" ]]; then
-    echo -e "** Installing python"
-    if ! install_python >/dev/null 2>"$LOGFILE"; then
-        clear
-        echo -e "$ERROR, Failed to install python, see log $LOGFILE"
-        exit 1
-    fi
-fi
-
-if [[ $ISPIPX == "$ERROR" ]]; then
-    echo -e "** Installing pipx"
-    if ! install_pipx >/dev/null 2>"$LOGFILE"; then
-        clear
-        echo -e "$ERROR, Failed to install pipx, see log $LOGFILE"
-        exit 1
-    fi
-fi
+    ;;
+esac
 
 if [[ $ISANSIBLE == "$ERROR" ]]; then
+    clear
     echo -e "** Installing ansible"
     if ! pipx install --include-deps ansible==$ANSIBLE_VERSION >/dev/null 2>"$LOGFILE"; then
         clear
